allow-lan: false
bind-address: '*'
cfw-bypass:
- localhost
- 127.*
- 10.*
- 172.16.*
- 172.17.*
- 172.18.*
- 172.19.*
- 172.20.*
- 172.21.*
- 172.22.*
- 172.23.*
- 172.24.*
- 172.25.*
- 172.26.*
- 172.27.*
- 172.28.*
- 172.29.*
- 172.30.*
- 172.31.*
- 192.168.*
- <local>
clash-for-android:
  append-system-dns: false
dns:
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - 180.184.1.1
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://101.101.101.101/dns-query
  - https://208.67.220.220/dns-query
  - https://114514.dns.nextdns.io/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 223.75.236.241/32
    - 182.43.124.6/32
    - 106.74.25.198/32
    - 183.192.65.101/32
  listen: 127.0.0.1:8853
  nameserver:
  - https://223.5.5.5/dns-query
  - https://223.6.6.6/dns-query
  - https://120.53.53.53/dns-query
  nameserver-policy:
    +.126.com: 119.29.29.29
    +.126.net: 119.29.29.29
    +.127.net: 119.29.29.29
    +.163.com: 119.29.29.29
    +.alibaba.com: 223.5.5.5
    +.alicdn.com: 223.5.5.5
    +.alipay.com: 223.5.5.5
    +.aliyun.com: 223.5.5.5
    +.baidu.com: 223.5.5.5
    +.bdstatic.com: 223.5.5.5
    +.bilibili.com: 119.29.29.29
    +.bilivideo.+: 119.29.29.29
    +.douyin.com: 180.184.1.1
    +.douyincdn.com: 180.184.1.1
    +.douyinpic.com: 180.184.1.1
    +.douyinvod.com: 180.184.1.1
    +.feishu.cn: 180.184.1.1
    +.hdslb.com: 119.29.29.29
    +.iqiyi.com: 119.29.29.29
    +.jd.com: 119.29.29.29
    +.netease.com: 119.29.29.29
    +.pphimalayanrt.com: 223.5.5.5
    +.qpic.cn: 119.29.29.29
    +.qq.com: 119.29.29.29
    +.taobao.com: 223.5.5.5
    +.tencent.com: 119.29.29.29
    +.tmall.com: 223.5.5.5
    +.weixin.com: 119.29.29.29
    st.dl.eccdnx.com: 223.5.5.5
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  use-hosts: true
external-controller: 127.0.0.1:9090
ipv6: false
log-level: info
mode: rule
port: 7890
proxies:
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V301U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1301
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.151.194.31
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V302U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1302
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.151.194.31
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V303U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1303
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.151.194.31
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V304U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1304
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.151.194.31
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V305U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1305
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.151.194.31
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V306U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1306
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.129
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V307U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1307
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.129
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V308U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1308
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.129
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V309U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1309
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.129
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V310U-1X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1310
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.129
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V320U-2X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1320
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V321U-2X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1321
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V322U-2X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1322
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V323U-2X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1323
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V326U-4X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1326
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V327U-4X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1327
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V328U-4X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1328
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° V329U-4X-BGP-HK-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1329
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V332U-1X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1332
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V333U-1X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1333
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V334U-1X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1334
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V335U-1X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1335
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V336U-2X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1336
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V337U-2X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1337
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V338U-2X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1338
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¯ğŸ‡µ V339U-2X-BGP-JP-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1339
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V350U-1X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1350
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.150.27.76
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V351U-1X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1351
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.150.27.76
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V352U-1X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1352
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.150.27.76
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V353U-1X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1353
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.150.27.76
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V354U-2X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1354
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V355U-2X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1355
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V356U-2X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1356
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V357U-2X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1357
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V358U-4X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1358
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¸ğŸ‡¬ V359U-4X-BGP-SG-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1359
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¨ğŸ‡³ V370U-2X-BGP-TW-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1370
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.130
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¨ğŸ‡³ V371U-2X-BGP-TW-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1371
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.130
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¨ğŸ‡³ V372U-2X-BGP-TW-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1372
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 120.236.198.130
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¨ğŸ‡³ V373U-2X-BGP-TW-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1373
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¨ğŸ‡³ V374U-2X-BGP-TW-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1374
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¨ğŸ‡³ V375U-2X-BGP-TW-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1375
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 121.14.131.180
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V380U-1X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1380
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V381U-1X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1381
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V382U-1X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1382
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V383U-1X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1383
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V386U-2X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1386
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V387U-2X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1387
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V388U-2X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1388
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡ºğŸ‡² V389U-2X-BGP-US-NF
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1389
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 223.113.53.152
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¬ğŸ‡§ V393U-1X-BGP-UK
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1393
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡©ğŸ‡ª V394U-1X-BGP-DE
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1394
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¹ğŸ‡· V396T-2X-BGP-TR
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1396
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: ğŸ‡¦ğŸ‡· V397T-2X-BGP-AR
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1397
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 117.24.6.238
  type: ssr
- cipher: chacha20-ietf
  name: åº”æ€¥ç»­è´¹èŠ‚ç‚¹-10X
  obfs: plain
  obfs-param: ''
  password: MAYING
  port: 1399
  protocol: auth_aes128_md5
  protocol-param: 16020:euFxN3
  server: 36.151.194.31
  type: ssr
proxy-groups:
- interval: 300
  name: auto-switch
  proxies:
  - ğŸ‡­ğŸ‡° V301U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V302U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V303U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V304U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V305U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V306U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V307U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V308U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V309U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V310U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V320U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V321U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V322U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V323U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V326U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V327U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V328U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V329U-4X-BGP-HK-NF
  - ğŸ‡¯ğŸ‡µ V332U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V333U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V334U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V335U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V336U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V337U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V338U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V339U-2X-BGP-JP-NF
  - ğŸ‡¸ğŸ‡¬ V350U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V351U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V352U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V353U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V354U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V355U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V356U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V357U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V358U-4X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V359U-4X-BGP-SG-NF
  - ğŸ‡¨ğŸ‡³ V370U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V371U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V372U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V373U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V374U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V375U-2X-BGP-TW-NF
  - ğŸ‡ºğŸ‡² V380U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V381U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V382U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V383U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V386U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V387U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V388U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V389U-2X-BGP-US-NF
  - ğŸ‡¬ğŸ‡§ V393U-1X-BGP-UK
  - ğŸ‡©ğŸ‡ª V394U-1X-BGP-DE
  - ğŸ‡¹ğŸ‡· V396T-2X-BGP-TR
  - ğŸ‡¦ğŸ‡· V397T-2X-BGP-AR
  - åº”æ€¥ç»­è´¹èŠ‚ç‚¹-10X
  tolerance: 100
  type: url-test
  url: https://tcgcsv.com
- interval: 300
  name: fallback-group
  proxies:
  - auto-switch
  - DIRECT
  type: fallback
  url: https://tcgcsv.com
- interval: 300
  name: load-balance
  proxies:
  - ğŸ‡­ğŸ‡° V301U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V302U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V303U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V304U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V305U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V306U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V307U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V308U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V309U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V310U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V320U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V321U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V322U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V323U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V326U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V327U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V328U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V329U-4X-BGP-HK-NF
  - ğŸ‡¯ğŸ‡µ V332U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V333U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V334U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V335U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V336U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V337U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V338U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V339U-2X-BGP-JP-NF
  - ğŸ‡¸ğŸ‡¬ V350U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V351U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V352U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V353U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V354U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V355U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V356U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V357U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V358U-4X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V359U-4X-BGP-SG-NF
  - ğŸ‡¨ğŸ‡³ V370U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V371U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V372U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V373U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V374U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V375U-2X-BGP-TW-NF
  - ğŸ‡ºğŸ‡² V380U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V381U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V382U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V383U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V386U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V387U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V388U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V389U-2X-BGP-US-NF
  - ğŸ‡¬ğŸ‡§ V393U-1X-BGP-UK
  - ğŸ‡©ğŸ‡ª V394U-1X-BGP-DE
  - ğŸ‡¹ğŸ‡· V396T-2X-BGP-TR
  - ğŸ‡¦ğŸ‡· V397T-2X-BGP-AR
  - åº”æ€¥ç»­è´¹èŠ‚ç‚¹-10X
  strategy: consistent-hashing
  type: load-balance
  url: https://tcgcsv.com
- name: manual-select
  proxies:
  - auto-switch
  - fallback-group
  - load-balance
  - DIRECT
  - ğŸ‡­ğŸ‡° V301U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V302U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V303U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V304U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V305U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V306U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V307U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V308U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V309U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V310U-1X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V320U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V321U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V322U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V323U-2X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V326U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V327U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V328U-4X-BGP-HK-NF
  - ğŸ‡­ğŸ‡° V329U-4X-BGP-HK-NF
  - ğŸ‡¯ğŸ‡µ V332U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V333U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V334U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V335U-1X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V336U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V337U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V338U-2X-BGP-JP-NF
  - ğŸ‡¯ğŸ‡µ V339U-2X-BGP-JP-NF
  - ğŸ‡¸ğŸ‡¬ V350U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V351U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V352U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V353U-1X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V354U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V355U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V356U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V357U-2X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V358U-4X-BGP-SG-NF
  - ğŸ‡¸ğŸ‡¬ V359U-4X-BGP-SG-NF
  - ğŸ‡¨ğŸ‡³ V370U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V371U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V372U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V373U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V374U-2X-BGP-TW-NF
  - ğŸ‡¨ğŸ‡³ V375U-2X-BGP-TW-NF
  - ğŸ‡ºğŸ‡² V380U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V381U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V382U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V383U-1X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V386U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V387U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V388U-2X-BGP-US-NF
  - ğŸ‡ºğŸ‡² V389U-2X-BGP-US-NF
  - ğŸ‡¬ğŸ‡§ V393U-1X-BGP-UK
  - ğŸ‡©ğŸ‡ª V394U-1X-BGP-DE
  - ğŸ‡¹ğŸ‡· V396T-2X-BGP-TR
  - ğŸ‡¦ğŸ‡· V397T-2X-BGP-AR
  - åº”æ€¥ç»­è´¹èŠ‚ç‚¹-10X
  type: select
redir-port: 7892
rules:
- DOMAIN-SUFFIX,tcgcsv.com,manual-select
- DOMAIN-SUFFIX,api.tcgcsv.com,manual-select
- DOMAIN-KEYWORD,tcg,manual-select
- MATCH,DIRECT
# secret: tcg-proxy-secret  # Disabled for testing
socks-port: 7891
